### PR TITLE
Clean up some partial matches.

### PR DESCRIPTION
**Pull request by craigcitro**
(I don't know a sane way to test this, which may make it futile?)

### CODE REVIEW

**Comment by hadley** [comment]
There are a few options you can set - I probably should set them somewhere

**Comment by craigcitro** [comment]
i tried doing combinations of `options(warnPartialMatchDollar = TRUE)` for detection, and `options(warn = 2)` to turn those into errors -- but the issue is that there are existing errors in dependencies. i didn't know a way to set "only turn this warning into an error for *this* package".

**Comment by hadley** [comment]
Fix all the dependent packages for me too? :wink:

**Comment by craigcitro** [comment]
well, **all** is a big commitment. :stuck_out_tongue:

**Pull request merged**
