### PR TITLE
Add `use_coverage()` function

### LINKED ISSUE #818: Switch from coveralls to codecov

### PR DESCRIPTION
**Pull request by jimhester**
To add codecov.io or coveralls.io to a project, also deprecate
`use_coveralls()`.

Closes #818

### CODE REVIEW

**Comment by hadley** [comment]
Looks good, but can you merge/rebase please?

**Comment by jimhester** [comment]
Rebased to 2cca68dbebeeb4123c14b75942f7b2537a67f318

**Comment by hadley** [comment]
Thanks!

**Comment by krlmlr** [comment]
I think the warnings in `R CMD check` relate to this pull request:

```
Undocumented arguments in documentation object 'use_coveralls'
  ‘pkg’

Undocumented arguments in documentation object 'infrastructure'
  ‘type’
```

They disappear if I revert 0840e0b.

**Pull request merged**
