### PR TITLE
Add default cache argument for lint

### PR DESCRIPTION
**Pull request by jimhester**
Combined with the bugfix in 2fbfee237c39c47cda15e93e96ef74a16b4bc40d this allows use of the caching functionality in lintr.

Reference timings (lints were previously cached)
```r
system.time(devtools::lint('../../../devtools', cache = FALSE))
#> Linting devtools.....................................................................................................................................
#>    user  system elapsed
#>  85.842   0.660  86.692

system.time(devtools::lint('../../../devtools', cache = TRUE))
#> Linting devtools.....................................................................................................................................
#>    user  system elapsed
#>   3.990   0.139   4.187

### CODE REVIEW

**Comment by hadley** [comment]
Does this need a bump in the version req for lintr?

**Comment by jimhester** [comment]
That is a good point, I will update this

**Comment by jimhester** [comment]
Ok lintr version bumped and requirement added to devtools.

**Comment by hadley** [comment]
And would you mind adding a bit more info about the cache? i.e. where it's saved and how to get rid of it.  Does the cache file needed to be added to `.gitignore` and/or `.Rbuildignore`?

**Comment by jimhester** [comment]
Ok this should be ok to merge now, let me know if the documentation is unclear.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
