### PR TITLE
Add function create_github_pat to make generating PATs super easy.

### PR DESCRIPTION
**Pull request by jeroen**
Homebrew has something similar and it is actually very convenient. Sends you directly to the form to generate the token with prefilled fields.

### CODE REVIEW

**Comment by jimhester** [comment]
I think this is good, but I think it really should be in [usethis](https://github.com/r-lib/usethis/pulls) rather than here.

**Comment by jeroen** [comment]
Are you sure? The function is not changing anything in R or in the package. It just sends the user to a webpage to generate a token. I thought it would be nice to accompany the `github_pat()` function.

What would it be called in usethis?

**Comment by jimhester** [comment]
`use_github_pat()`?

**Comment by jeroen** [comment]
But that implies that the github pat is actually installed? That is actually a different feature. I would expect you would have to call `use_github_pat("2b7a27ced93ca519")` or something and then it would modify your Rprofile or so?

The PR above only opens a browser window.

**Comment by hadley** [comment]
This feels like a usethis function to me - maybe `browse_github_pat()`?  We could eventually have `use_github_pat()` once we have more wrappers around modifying `.Renviron`

**Comment by jimhester** [comment]
Closing this here, I opened an usethis issue for it https://github.com/hadley/devtools/pull/1665

**Pull request closed without merging**
