### PR TITLE
Augmented update_packages to update those installed from remote repos

### PR DESCRIPTION
**Pull request by bearloga**
- Moved update_packages() from deps.R to update.R
- Make pkgs argument optional in update_packages to allow updating all
installed packages (installed from CRAN or otherwise)
- Added utility functions: get_local_info() and get_remote_sha1() which
are used in update_remotes()

<strike>P.S. It looks like **git2r** is getting a `remote_ls` (https://github.com/ropensci/git2r/pull/172) but that hasn't propagated yet, so I'm using `git ls-remote` at OS level for now.</strike> **Update**: using `git2r::remote_ls()` now

### CODE REVIEW

**Comment by bhive01** [comment]
The errors for this are: 
```shell
* checking Rd cross-references ... WARNING
Missing link or links in documentation object 'package_deps.Rd':
  ‘install_packages’
See section 'Cross-references' in the 'Writing R Extensions' manual.
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... WARNING
Documented arguments not in \usage in documentation object 'update_packages':
  ‘ask’
Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```
Looks like the build issue is related to documentation. 

I'm kind of awful at the roxygen stuff, but it looks like the issue is on line 14/15 of update.R. The ask parameter is not used in update_packages(), but in update_remotes(). Maybe delete that and see if it builds?

**Comment by bhive01** [comment]
Bitchin'.

**Comment by hadley** [comment]
@jimhester will take the first round of review, and then I'll take a look

**Comment by hadley** [comment]
Hi @bearloga - we really appreciate the pull request but it's currently too far from how we'd implement it that I don't think it's useful to iterate here. In a few minutes, I'll create a new issue describing the problem, and quickly dumping my thoughts on the issue. We'll probably tackle it ourselves for 1.11, but thanks for the idea and the sketch implementation that shows it shouldn't be too much work!

**Pull request closed without merging**
