### PR TITLE
Fix typo on README.md

### PR DESCRIPTION
**Pull request by alejandrodumas**

### CODE REVIEW

**Comment by hadley** [comment]
What's the typo?

**Comment by robertzk** [comment]
Looks like he just removed a newline.

**Comment by alejandrodumas** [comment]
`You can can use it` _can_ is repeated.

**Comment by hadley** [comment]
Thanks!

**Comment by wch** [comment]
This is a real-life example of a classic visual illusion!

http://www.moillusions.com/test-sharp-minded/
http://planetperplex.com/en/item/a-bird/

**Pull request closed without merging**
