### PR TITLE
use_testthat adds example test file

### PR DESCRIPTION
**Pull request by krlmlr**

### CODE REVIEW

**Comment by hadley** [comment]
Motivation?

**Comment by krlmlr** [comment]
- Example file that can be extended without having to look up `testthat` syntay
- `R CMD check` doesn't start failing

**Comment by hadley** [comment]
From my perspective, it's just a file that I always have to remember to delete. That's why `create()` no longer makes a package doc template.

**Comment by krlmlr** [comment]
How about

```
use_test <- function(name, pkg = ".")
```

similar to `use_vignette`?

**Comment by hadley** [comment]
I like it! I'll close this PR since I don't think there will be much overlap.

**Pull request closed without merging**
