### PR TITLE
Remove deprecated `args` argument from `install_git()`

### LINKED ISSUE #1373: Cannot pass args through install_git
The `install_git` function has an argument that is called `args` and is deprecated. The problem is that `install_git` passes arguments through to `install` via `...` and `args` is a valid argument I want to pass to `install`. 

I tried using `INSTALL_opts` which should work it's way down to `install.packages`, but that doesn't seem to work. I believe a solution could remove the current deprecated `args` argument from `install_git`. Here is an example of some code that I'm having trouble with:

```
devtools::install_git("a.repo.url.here", 
                      branch="master", 
                      dependencies=FALSE,
                      args=c("--no-multiarch"))
Error: Command failed (1)
In addition: Warning message:
`args` is deprecated 
```

**Trying INSTALL_opts**

```
devtools::install_git("a.repo.url.here", 
                      branch="master", 
                      dependencies=FALSE,
                      INSTALL_opts=c("--no-multiarch"))
```

`--no-multiarch` is ignored completely

```
Session info -------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, mingw32             
 ui       RStudio (0.99.441)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-10-09                  

Packages -------------------------------------------------------------
 package  * version date       source        
 devtools   1.12.0  2016-06-24 CRAN (R 3.2.5)
 digest     0.6.10  2016-08-02 CRAN (R 3.2.5)
 git2r      0.15.0  2016-05-11 CRAN (R 3.2.5)
 memoise    1.0.0   2016-01-29 CRAN (R 3.2.5)
 withr      1.0.2   2016-06-20 CRAN (R 3.2.5)
```

### PR DESCRIPTION
**Pull request by ReportMort**
resolves #1373 and also fixes an issue where the `quiet` argument was explicitly stated in `try_install_remote()` and throwing error if not explicitly provided upstream.

### CODE REVIEW

**Comment by hadley** [comment]
Could you please take a look at the build failures?

**Comment by ReportMort** [comment]
I've taken a look at build failures and resubmitted PR as #1390. There's still a failure on Travis, but seems unrelated. Thanks for taking a look.

**Comment by jimhester** [comment]
@ReportMort You don't need to resubmit, if you push more commits to the same branch the PR was on they will be added to the existing PR.

**Comment by ReportMort** [comment]
Thanks @jimhester. I'm aware. This was sort of a dumb thing on my part. I reset hard on some commits and GitHub automatically closed this PR and opened a new one. I can closed #1390 and re-opened this guy.

**Comment by jimhester** [comment]
Thanks! Merged in 2636e2a4

**Pull request closed without merging**
