### PR TITLE
add timestamp to messages in 'build_win'

### PR DESCRIPTION
**Pull request by achubaty**
A couple reasons to add a timestamp:
1. When submitting to win-builder, package build can sometimes take a while prior to submission and I like having an indication of how long it takes.
2. I sometimes submit to win-builder and if don't get an email within the 30-60 minutes or I switch tasks while waiting for the email, it's nice to see exactly how long ago the package was submitted.

### CODE REVIEW

**Comment by hadley** [comment]
I like this idea, but I think the timestamp needs to only appear in one place, and I'd prefer something custom created with `strftime()` + `Sys.time()`. Maybe "10:30pm (2016-10-11)".  

While you're in there, it might be worth updating the time limit. I'm seeing times of more like 15-30 minutes lately.

**Comment by achubaty** [comment]
@hadley good suggestions. I've updated as requested.

Note: there's an unrelated error in the travis checks on R-devel that's causing a failure, as well as some unrelated errors locally:

```r
checking tests ... ERROR
Running the tests in ‘tests/test-that.R’ failed.
Last 13 lines of output:
  
  
  testthat results ================================================================
  OK: 409 SKIPPED: 0 FAILED: 6
  1. Failure: install_bioc (@test-bioconductor.r#39) 
  2. Error: install_bioc (@test-bioconductor.r#40) 
  3. Error: github info and links can be queried and manipulated (@test-github-connections.R#49) 
  4. Error: github_info() prefers, but doesn't require, remote named 'origin' (@test-github-connections.R#93) 
  5. Error: install on packages adds metadata (@test-remote-metadata.R#15) 
  6. Failure: remote_sha.github_remote returns expected value if remote does exist (@test-remotes.r#75) 
  
  Error: testthat unit tests failed
  Execution halted
R CMD check results
1 error  | 0 warnings | 0 notes

R CMD check succeeded
```

I have all the package dependencies (including Suggests) installed and up to date.

**Comment by hadley** [comment]
@jimhester can you please squash-merge by hand?

**Comment by jimhester** [comment]
Thanks!

Merged by hand at https://github.com/hadley/devtools/commit/95a1ad66ac58ce554413334d31a239aed7ceb22d, so closing this PR.

**Pull request closed without merging**
