### PR TITLE
Export RCMD function so it can be used in other packages.

### LINKED ISSUE #698: Export RCMD and possibly R functions.
In order to get compiled code coverage working https://github.com/jimhester/covr/issues/9 I need to compile and test the code in an R subprocess.  I attempted to write a simple function but was running into issues getting `R CMD check` to work properly.

using `devtools:::RCMD` does run without errors [R/subprocess.R#L54](https://github.com/jimhester/covr/blob/f7ad15b5ff283d960d3d68bbb171ca050c085587/R/subprocess.R#L54) (https://travis-ci.org/jimhester/covr/builds/46911723) but as that function is un-exported I cannot use it without a NOTE.

If you are ok with it being an exported function I can make a pull request to add the documentation and export it, just let me know.

### PR DESCRIPTION
**Pull request by jimhester**
Fixes #698.

I did not add a note to NEWS.md because it is currently formatted for the release.  Once the release it out I can rebase this pull and add a NEWS item.

Let me know if you need me to tweak anything.

### CODE REVIEW

**Comment by hadley** [comment]
devtools 1.7.0 is still in CRAN limbo, but this looks good to do once it's out.  (If it gets rejected, I'll try and remember to include this pull request before resubmitting)

**Comment by hadley** [comment]
Looks good. Can you please add a bullet to NEWS now?

**Comment by jimhester** [comment]
Ok this should be good to do now.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
