### PR TITLE
Build on 3.0.3

### PR DESCRIPTION
**Pull request by jimhester**

### CODE REVIEW

**Comment by hadley** [comment]
Still fails due to lack of `trimws()`

**Comment by jimhester** [comment]
It is working now, but the check is failing because suggested packages are not available

**Comment by krlmlr** [comment]
I'm switching to using `remotes` in r-appveyor, perhaps r-travis could do the same?

**Comment by hadley** [comment]
Should we take another pass at this, or go for R 3.1?

**Comment by hadley** [comment]
Superseded by #1560

**Pull request closed without merging**
